#!/usr/bin/env bash
# (Auto-generated by build.sh)
# header.sh

# ci.sh (https://github.com/nho-sh/ci.sh/)
# A single-file, batteries included, opinionated CI entrypoint bash script

# LICENSE: MIT
#   https://github.com/nho-sh/ci.sh/blob/main/LICENSE

# Sense check: are we running in bash? or something compatible?
if [ -z "$BASH_VERSION" ]; then
    echo "ci.sh only works in bash. (If you want to force run, set BASH_VERSION=dummy)"
    exit 100
fi
# utilities.sh

function isTruthy() {
    case "$1" in
        "1" | "true" | "True" | "TRUE" | "yes" | "on")
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

function isFalsy() {
    case "$1" in
        "" | "0" | "false" | "False" | "FALSE" | "no" | "off")
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# constants.sh

_CISH_RUNROOT=$(pwd -P)
_CISH_CI_SUITE="" # teamcity/github/gitlab

if [ "$TEAMCITY_VERSION" != "" ]; then
    _CISH_CI_SUITE="teamcity"
elif [ "$GITHUB_ACTIONS" = "true" ]; then
    _CISH_CI_SUITE="github"
elif [ "$GITLAB_CI" = "true" ]; then
    _CISH_CI_SUITE="gitlab"
fi
# env.sh

: "${CISH_DEBUG:=}"
: "${CISH_ENTRY_MESSAGE:=Starting CI}"
: "${CISH_EXIT_MESSAGE:=bye.}"
: "${CISH_INDENT_SIZE:=2}"
: "${CISH_OUTPUT_DIR:=$_CISH_RUNROOT/ci-output}"
: "${CISH_OUTPUT_LOG:=$CISH_OUTPUT_DIR/ci.log}"
: "${CISH_PRINT_SYSTEM_INFO:=no}"
: "${CISH_PRINT_DURATION:=yes}"
: "${CISH_PRINT_EMOJI:=yes}"

# Debug log all values
if [ "$CISH_DEBUG" = 1 ]; then
    echo "CISH_DEBUG enabled"
    echo
    echo "CISH_DEBUG=$CISH_DEBUG"
    echo "CISH_ENTRY_MESSAGE=$CISH_ENTRY_MESSAGE"
    echo "CISH_EXIT_MESSAGE=$CISH_EXIT_MESSAGE"
    echo "CISH_OUTPUT_DIR=$CISH_OUTPUT_DIR"
    echo "CISH_OUTPUT_LOG=$CISH_OUTPUT_LOG"
    echo "CISH_PRINT_DURATION=$CISH_PRINT_DURATION"
    echo "CISH_PRINT_SYSTEM_INFO=$CISH_PRINT_SYSTEM_INFO"
fi

# Sense checks

# Is the output folder not something weird?
if [ "$CISH_OUTPUT_DIR" = "" ] || [ "$CISH_OUTPUT_DIR" = "/ci-output" ]; then
    echo "Something is wrong with setting up the output dir. This is wrong: '$CISH_OUTPUT_DIR'"
    exit 101
fi

# Make a build output folder if it does not exist yet
mkdir -p "$CISH_OUTPUT_DIR"

# Delete files in the output folder as best as we can
rm -rf $CISH_OUTPUT_DIR/* || true

# From this point on, all output is captured by exec
# and sent via tee to both file and the terminal
exec > >(tee "$CISH_OUTPUT_LOG") 2>&1
# log.sh

# Every active section that is begun, will be recorded here,
# so we know what it is, when we have an error.
ACTIVE_SECTION_FILE="/tmp/cish_lastblock_$( cksum <(pwd) | cut -f 1 -d ' ' )"

# Test if we can adjust this file or not
if touch "$ACTIVE_SECTION_FILE" 2>/dev/null; then
    rm -f "$ACTIVE_SECTION_FILE"
else
    # Disable this functionality, cannot write to /tmp :(
    ACTIVE_SECTION_FILE=""
fi

if isTruthy "$CISH_PRINT_EMOJI"; then
    _CISH_EMOJI_OKAY="✅"
    _CISH_EMOJI_ERROR="❌"
    _CISH_EMOJI_WARN="⚠️"
    _CISH_EMOJI_BEGIN="🚀" # 🚀 🔷 ▶
    _CISH_EMOJI_END="🏁"
    _CISH_EMOJI_TOOLS="🛠️"
    _CISH_EMOJI_PC="🖥️"
    _CISH_EMOJI_CHRONO="⏱️"
else
    _CISH_EMOJI_OKAY="✓"
    _CISH_EMOJI_ERROR="X"
    _CISH_EMOJI_WARN="!"
    _CISH_EMOJI_BEGIN=">"
    _CISH_EMOJI_END=""
    _CISH_EMOJI_TOOLS=""
    _CISH_EMOJI_PC=""
    _CISH_EMOJI_CHRONO=""
fi

# TODO: make this work, so that the base section headers are underlined
# # TTY active?
# if [ -t 1 ]; then
#     _CISH_UNDERLINE_OPEN="\033[4m"
#     _CISH_UNDERLINE_CLOSE="\033[0m"
# else
#     _CISH_UNDERLINE_OPEN=""
#     _CISH_UNDERLINE_CLOSE=""
# fi

if [ -n "$_CISH_CI_SUITE" ]; then
    function cishLog() {
        if [ "$1" != "" ]; then

            if [ "$_CISH_CI_SUITE" = 'teamcity' ]; then
                echo "$(date '+%Y-%m-%d %H:%M:%S') $*"

            elif [ "$_CISH_CI_SUITE" = 'github' ]; then
                # Timestamp the logs
                TS=$(date --iso-8601=s)
                echo "[$TS] $*"

            elif [ "$_CISH_CI_SUITE" = 'gitlab' ]; then
                # Timestamp the logs
                TS=$(date --iso-8601=s)
                echo "[$TS] $*"
            fi

        fi
    }
else
    # TODO: allow changing this line format or a flag to include the current time?
    function cishLog() {
       echo "$@"
    }
fi

_CISH_INDENT_LEVEL=0

if [ -n "$_CISH_CI_SUITE" ]; then
    function logSectionBegin() {
        if [ -n "$ACTIVE_SECTION_FILE" ]; then
            echo "$1" > "$ACTIVE_SECTION_FILE"
        fi

        if [ "$_CISH_CI_SUITE" = 'teamcity' ]; then
            echo "##teamcity[blockOpened name='$1']"

        elif [ "$_CISH_CI_SUITE" = 'github' ]; then
            echo "::block::$1"

        elif [ "$_CISH_CI_SUITE" = 'gitlab' ]; then
            echo -e "section_start:$(date +%s):$1\r"

        else
            echo "Start of $1"
        fi
    }
    function logSectionEnd() {
        if [ "$_CISH_CI_SUITE" = 'teamcity' ]; then
            echo "##teamcity[blockClosed name='$1']"

        elif [ "$_CISH_CI_SUITE" = 'github' ]; then
            echo "::endgroup::"

        elif [ "$_CISH_CI_SUITE" = 'gitlab' ]; then
            echo -e "section_end:$(date +%s):$1\r"

        else
            echo "End of $1"
        fi
    }
else
   function logSectionBegin() {
        local label="$1"

        if [ -n "$ACTIVE_SECTION_FILE" ]; then
            echo "$1" > "$ACTIVE_SECTION_FILE"
        fi

        printf "%*s$_CISH_EMOJI_BEGIN %s $_CISH_EMOJI_BEGIN\n" $((_CISH_INDENT_LEVEL * CISH_INDENT_SIZE)) "" "$label"
        ((_CISH_INDENT_LEVEL++))
   }
   function logSectionEnd() {
        ((_CISH_INDENT_LEVEL--))
        local label="$1"
        printf "%*s$_CISH_EMOJI_END %s $_CISH_EMOJI_END\n" $((_CISH_INDENT_LEVEL * CISH_INDENT_SIZE)) "" "$label"
   }
fi

function _cishGetLastSection() {
    if [ -n "$ACTIVE_SECTION_FILE" ]; then
        cat "$ACTIVE_SECTION_FILE"
    else
        echo "(failed to detect)"
    fi
}
# tweaks.sh

# Docker: do not use progress bars in CI, and flood the logs
export BUILDKIT_PROGRESS=plain

# No TTY connected?
if [ ! -t 1 ]; then
    # Do not use colored output if there is not TTY, only causes trouble
    export NO_COLOR=1

    # Simplify terminal output, to avoid trouble
    export TERM=dumb

    # TODO What else can we by default make better in non-TTY?
fi
# utilities.sh

function printSystemInfo {
    # User wants it printed?
    if isFalsy "$CISH_PRINT_SYSTEM_INFO"; then
        return 0
    fi

    function printVersion() {
        local name="$1"
        shift

        if command -v "$name" >/dev/null 2>&1; then
            echo "$name: $("$@" 2>&1 | head -n 3)"
            echo
        fi
    }

    logSectionBegin 'System Info'

    logSectionBegin "$_CISH_EMOJI_TOOLS Installed applications"

    printVersion node node --version
    printVersion npm npm --version
    printVersion java java -version
    printVersion docker docker --version
    printVersion git git --version
    printVersion make make --version
    printVersion gcc gcc --version
    printVersion python3 python3 --version

    logSectionEnd "$_CISH_EMOJI_TOOLS Installed applications"

    logSectionBegin "$_CISH_EMOJI_PC Running environment"

    echo "Working dir:   $(pwd)"
    echo "Current user:  $USER ($UID) / $(id -g -n) ($(id -g))"

    echo "Hostname:      $(hostname)"
    echo "OS:            $(uname -a)"
    echo "Kernel:        $(uname -r)"
    echo "Architecture:  $(uname -m)"
    echo "Uptime:        $(uptime -p 2>/dev/null || uptime)"
    # TODO: nice memory/disk summary

    logSectionEnd "$_CISH_EMOJI_PC Running environment"

    logSectionEnd 'System Info'
}

function cishFileExists() {
    [ -f "$1" ]
}

function cishFileNotExists() {
    [ ! -f "$1" ]
}
function cishFileEmpty() {
    [ -f "$1" ] && [ ! -s "$1" ]
}

function cishFileNotEmpty() {
    [ -f "$1" ] && [ -s "$1" ]
}

function cishUserNotification {
    cishLog "$1"

    MSG="$1"

    # Subshell, so failure here is not a showstopper
    (
        # Only execute command if it exists

        # linux
        if command -v notify-send >/dev/null 2>&1; then
            notify-send --hint=int:transient:1 "$MSG"

        # mac
        elif command -v terminal-notifier >/dev/null 2>&1; then
            terminal-notifier -title "ci.sh" -message "$MSG"

        # mac fallback using AppleScript (no dependencies)
        elif [ "$(uname)" = "Darwin" ]; then
            osascript -e "display notification \"$MSG\" with title \"ci.sh\""

        fi

    ) || true
}
# base.sh

cishLog "$CISH_ENTRY_MESSAGE"

# Check if output folder exists
if [ ! -d "$CISH_OUTPUT_DIR" ]; then
    # TODO: test if we can write to the folder
    cishLog "$CISH_OUTPUT_DIR does not exist. mkdir it first"
    exit 102
fi


# Default missing functions
type -t cish_setup > /dev/null
if [ "$?" != "0" ]; then
    function cish_setup() {
        cishLog "$_CISH_EMOJI_WARN cish_setup is not defined, skipped"
    }
fi

type -t cish_run > /dev/null
if [ "$?" != "0" ]; then
    function cish_run() {
        cishLog "$_CISH_EMOJI_WARN cish_run is not defined, skipped"
    }
fi

type -t cish_teardown > /dev/null
if [ "$?" != "0" ]; then
    function cish_teardown() {
        cishLog "$_CISH_EMOJI_WARN cish_teardown is not defined, skipped"
        if [ "$1" != "" ]; then
            cishLog "  but there was an error: $0" # $0 = exit code
        fi
    }
fi

# Variables
SETUP_EXIT_CODE=0
SETUP_SUMMARY=""
RUN_EXIT_CODE=0
RUN_SUMMARY=""
TEARDOWN_EXIT_CODE=0
TEARDOWN_SUMMARY=""

{
    logSectionBegin 'Setup'

    printSystemInfo

    cish_setup
    SETUP_EXIT_CODE=$?

    if [ "$SETUP_EXIT_CODE" -eq 0 ]; then
        cishLog "Setup okay"
        SETUP_SUMMARY="$_CISH_EMOJI_OKAY"
    else
        SETUP_SUMMARY="$_CISH_EMOJI_ERROR"

        if [ "$_CISH_CI_SUITE" = 'teamcity' ]; then
            # Teamcity compatible message
            # https://www.jetbrains.com/help/teamcity/service-messages.html#Reporting+Build+Status
            echo "##teamcity[message text='Setup failed in $(_cishGetLastSection) exitcode=$SETUP_EXIT_CODE' errorDetails='See lines above' status='ERROR']"

            # TODO: add gitlab/github

        else
            cishLog "$_CISH_EMOJI_ERROR Setup failed in $(_cishGetLastSection) exitcode=$SETUP_EXIT_CODE"

        fi
    fi

    logSectionEnd 'Setup'
}

echo # add some whitespace in the logs

{
    # Only run if setup didn't error
    if [ "$SETUP_EXIT_CODE" = "0" ]; then
        logSectionBegin 'Run'

        cish_run
        RUN_EXIT_CODE=$?

        if [ "$RUN_EXIT_CODE" = "0" ]; then
            cishLog "Run successful"
            RUN_SUMMARY="$_CISH_EMOJI_OKAY"
        else
            RUN_SUMMARY="$_CISH_EMOJI_ERROR"

            if [ "$_CISH_CI_SUITE" = 'teamcity' ]; then
                # Teamcity compatible message
                # https://www.jetbrains.com/help/teamcity/service-messages.html#Reporting+Build+Status
                echo "##teamcity[message text='Run failed in $(_cishGetLastSection) exitcode=$RUN_EXIT_CODE' errorDetails='See lines above' status='ERROR']"

                # TODO: add gitlab/github

            else
                cishLog "$_CISH_EMOJI_ERROR Run failed in $(_cishGetLastSection) exitcode=$RUN_EXIT_CODE"

            fi
        fi

        logSectionEnd 'Run'
    else
        cishLog "$_CISH_EMOJI_WARN Run skipped, there is an error"
    fi
}

echo # add some whitespace in the logs

{
    logSectionBegin "Teardown"

    # Always run teardown, but pass error message
    # to teardown function
    #
    # The teardown does not need a subshell, because it should not be running
    # with `set -e` anyway, so that it can clean up and log as much as possible
    # By not running in a subshell, any bug in the teardown step will be immediatly visible
    cish_teardown "$SETUP_EXIT_CODE" "$RUN_EXIT_CODE"
    TEARDOWN_EXIT_CODE=$?

    if [ "$TEARDOWN_EXIT_CODE" = "0" ]; then
        cishLog "Teardown okay"
        TEARDOWN_SUMMARY="$_CISH_EMOJI_OKAY"
    else
        TEARDOWN_SUMMARY="$_CISH_EMOJI_ERROR"

        if [ "$_CISH_CI_SUITE" = 'teamcity' ]; then
            # Teamcity compatible message
            # https://www.jetbrains.com/help/teamcity/service-messages.html#Reporting+Build+Status
            echo "##teamcity[message text='Teardown failed in $(_cishGetLastSection) exitcode=$TEARDOWN_EXIT_CODE' errorDetails='See lines above' status='ERROR']"

            # TODO: add gitlab/github

        else
            cishLog "$_CISH_EMOJI_ERROR Teardown failed in $(_cishGetLastSection) exitcode=$TEARDOWN_EXIT_CODE"

        fi

    fi

    logSectionEnd 'Teardown'
}

echo # whitespace for clarity

# Calculate how long it ran
if isTruthy "$CISH_PRINT_DURATION"; then
    DURATION=$SECONDS
    cishLog "Finished after $(($DURATION / 60))m $(($DURATION % 60))s $_CISH_EMOJI_CHRONO"
fi

# Log an additional exit message if defined
if [ "$CISH_EXIT_MESSAGE" != "" ]; then
    cishLog "$CISH_EXIT_MESSAGE"
fi

echo "S:$SETUP_SUMMARY R:$RUN_SUMMARY T:$TEARDOWN_SUMMARY"

# coalesce with teardown exit code
FINAL_EXIT_CODE=0
[ $SETUP_EXIT_CODE -ne 0 ] && FINAL_EXIT_CODE=$SETUP_EXIT_CODE
[ $RUN_EXIT_CODE -ne 0 ] && FINAL_EXIT_CODE=$RUN_EXIT_CODE
[ $TEARDOWN_EXIT_CODE -ne 0 ] && FINAL_EXIT_CODE=$TEARDOWN_EXIT_CODE
return $FINAL_EXIT_CODE
